//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DBContainer : DbContext
    {
        public DBContainer()
            : base("name=DBContainer")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Object> ObjectSet { get; set; }

        public System.Data.Entity.DbSet<HMS.Models.Person> People { get; set; }

        public System.Data.Entity.DbSet<HMS.Models.LocalCase> LocalCases { get; set; }

        public System.Data.Entity.DbSet<HMS.Models.Patient> Patients { get; set; }

        public System.Data.Entity.DbSet<HMS.Models.Room> Rooms { get; set; }

        public System.Data.Entity.DbSet<HMS.Models.User> Users { get; set; }
    }
}
