//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int Id { get; set; }
        public System.DateTime timecreate { get; set; }
        public System.DateTime timemodify { get; set; }
        public bool isactive { get; set; }
    }
}
