//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class User : Person
    {
        //Leerer Konstruktor wie immer
        //MW
        public User() { }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User(int id, System.DateTime timecreate, System.DateTime timemodify, bool isactive, string prename, string surname, string phone, 
            string email, string gender, string street, string city, string zip, DateTime dateofbirth, string password, string rolename, bool accessright1, bool accessright2, bool accessright3) 
            : base(id, timecreate, timemodify, isactive, prename, surname, phone, email, gender, street, city, zip, dateofbirth)
        {
            this.LocalCase = new HashSet<LocalCase>();
            this.password = password;
            this.rolename = rolename;
            this.accessright1 = accessright1;
            this.accessright2 = accessright2;
            this.accessright3 = accessright3;

            Exception rolenameException = new Exception("Ungültige Funktion");

            if (!((gender == "Arzt") || (gender == "Oberarzt") || (gender == "Schwester") || (gender == "Pfleger") || (gender == "Admin") || (gender == "Reinigungspersonal")))
            {
                throw rolenameException;
            }
        }

        [Required(ErrorMessage = "Bitte geben Sie ein Passwort ein.")]
        [Display(Name = "Passwort")]
        public string password { get; set; }
        [Required(ErrorMessage = "Bitte tätigen Sie eine Eingabe.")]
        [Display(Name = "Funktion")]
        [RegularExpression(@"\bArzt\b|\bOberarzt\b|\bSchwester\b|\bPfleger\b|\bAdmin\b|\bReinigungspersonal\b", ErrorMessage = "Bitte geben Sie eins der foglenden Attribute ein: Oberarzt, Arzt, Admin, Schwester, Pfleger, Reinigungspersonal.")]
        public string rolename { get; set; }
        [Display(Name = "Rechte1")]
        public bool accessright1 { get; set; }
        [Display(Name = "Rechte2")]
        public bool accessright2 { get; set; }
        [Display(Name = "Rechte3")]
        public bool accessright3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalCase> LocalCase { get; set; }
    }
}
